using System;
using FluentValidation;
using System.Collections;
using System.Linq.Expressions;
using System.Collections.Generic;

namespace Berger.Extensions.Notification
{
    public interface INotification
    {
        int Count();
        bool IsValid();
        bool IsInvalid();
        IReadOnlyCollection<NotificationViewModel> Messages { get; }
        void AddNotification(string property, string message);
        void AddNotification(string property, string message, params object[] parameters);
        void AddNotification(NotificationViewModel notification);
        void AddNotifications(ICollection<NotificationViewModel> notifications);
        void AddNotifications(IList<NotificationViewModel> notifications);
        void AddNotifications(IReadOnlyCollection<NotificationViewModel> notifications);
        void ClearNotifications();
        bool HasNotifications();
        void CustomCreate(string property, string message);
        void IfAreEquals<T>(T model, Expression<Func<T, double>> selector, double value, string message = "");
        void IfAreEquals(double val, double value, string objectName, string message = "");
        void IfAreEquals<T>(T model, Expression<Func<T, DateTime>> selector, DateTime value, string message = "");
        void IfAreEquals(decimal val, decimal value, string objectName, string message = "");
        void IfAreEquals<T>(T model, Expression<Func<T, float>> selector, float value, string message = "");
        void IfAreEquals(float val, float value, string objectName, string message = "");
        void IfAreEquals<T>(T model, Expression<Func<T, int>> selector, int value, string message = "");
        void IfAreEquals<T>(T model, Expression<Func<T, decimal>> selector, decimal value, string message = "");
        void IfAreEquals(int val, int value, string objectName, string message = "");
        void IfAreEquals<T>(T model, Expression<Func<T, string>> selector, string text, string message = "");
        void IfAreEquals(string val, string text, string objectName, string message = "");
        void IfAreEquals(DateTime val, DateTime value, string objectName, string message = "");
        void IfCollectionIsNull<T>(T model, Expression<Func<T, IEnumerable>> selector, string message = "");
        void IfCollectionIsNull(IEnumerable val, string objectName, string message = "");
        void IfCollectionIsNullOrEmpty<T>(T model, Expression<Func<T, IEnumerable<T>>> selector, string message = "");
        void IfCollectionIsNullOrEmpty<T>(IEnumerable<T> val, string objectName, string message = "");
        void IfContains<T>(T model, Expression<Func<T, string>> selector, string text, string message = "");
        void IfContains(string val, string text, string objectName, string message = "");
        void IfEnumInvalid<T>(T model, Expression<Func<T, Enum>> selector, string message = "");
        void IfEnumInvalid(Enum val, string objectName, string message = "");
        void IfEqualsZero(decimal val, string objectName, string message = "");
        void IfEqualsZero(int val, string objectName, string message = "");
        void IfEqualsZero<T>(T model, Expression<Func<T, int>> selector, string message = "");
        void IfEqualsZero<T>(T model, Expression<Func<T, decimal>> selector, string message = "");
        void IfEqualsZero<T>(T model, Expression<Func<T, float>> selector, string message = "");
        void IfEqualsZero(float val, string objectName, string message = "");
        void IfFalse<T>(T model, Expression<Func<T, bool>> selector, string message = "");
        void IfFalse(bool val, string objectName, string message = "");
        void IfGreaterOrEqualsThan<T>(T model, Expression<Func<T, double>> selector, double number, string message = "");
        void IfGreaterOrEqualsThan(double val, double number, string objectName, string message = "");
        void IfGreaterOrEqualsThan<T>(T model, Expression<Func<T, float>> selector, float number, string message = "");
        void IfGreaterOrEqualsThan(float val, float number, string objectName, string message = "");
        void IfGreaterOrEqualsThan<T>(T model, Expression<Func<T, decimal>> selector, decimal number, string message = "");
        void IfGreaterOrEqualsThan<T>(T model, Expression<Func<T, DateTime>> selector, DateTime date, string message = "");
        void IfGreaterOrEqualsThan<T>(T model, Expression<Func<T, int>> selector, int number, string message = "");
        void IfGreaterOrEqualsThan(int val, int number, string objectName, string message = "");
        void IfGreaterOrEqualsThan(decimal val, decimal number, string objectName, string message = "");
        void IfGreaterOrEqualsThan(DateTime val, DateTime date, string objectName, string message = "");
        void IfGreaterThan(DateTime val, DateTime max, string objectName, string message = "");
        void IfGreaterThan(float val, float max, string objectName, string message = "");
        void IfGreaterThan<T>(T model, Expression<Func<T, DateTime>> selector, DateTime max, string message = "");
        void IfGreaterThan<T>(T model, Expression<Func<T, int>> selector, int max, string message = "");
        void IfGreaterThan(int val, int max, string objectName, string message = "");
        void IfGreaterThan(double val, double max, string objectName, string message = "");
        void IfGreaterThan<T>(T model, Expression<Func<T, double>> selector, double max, string message = "");
        void IfGreaterThan<T>(T model, Expression<Func<T, float>> selector, float max, string message = "");
        void IfGreaterThan(decimal val, decimal max, string objectName, string message = "");
        void IfGreaterThan<T>(T model, Expression<Func<T, decimal>> selector, decimal max, string message = "");
        void IfInvalidContract<T>(T model, AbstractValidator<T> validator);
        void IfLengthGreaterThan(string val, int max, string objectName, string message = "");
        void IfLengthGreaterThan<T>(T model, Expression<Func<T, string>> selector, int max, string message = "");
        void IfLengthLowerThan(string val, int min, string objectName, string message = "");
        void IfLengthLowerThan<T>(T model, Expression<Func<T, string>> selector, int min, string message = "");
        void IfLengthNoEqual<T>(T model, Expression<Func<T, string>> selector, int length, string message = "");
        void IfLengthNoEqual(string val, int length, string objectName, string message = "");
        void IfLowerOrEqualsThan(float val, float number, string objectName, string message = "");
        void IfLowerOrEqualsThan(DateTime val, DateTime date, string objectName, string message = "");
        void IfLowerOrEqualsThan<T>(T model, Expression<Func<T, int>> selector, int number, string message = "");
        void IfLowerOrEqualsThan<T>(T model, Expression<Func<T, double>> selector, double number, string message = "");
        void IfLowerOrEqualsThan<T>(T model, Expression<Func<T, DateTime>> selector, DateTime date, string message = "");
        void IfLowerOrEqualsThan<T>(T model, Expression<Func<T, decimal>> selector, decimal number, string message = "");
        void IfLowerOrEqualsThan(decimal val, decimal number, string objectName, string message = "");
        void IfLowerOrEqualsThan<T>(T model, Expression<Func<T, float>> selector, float number, string message = "");
        void IfLowerOrEqualsThan(int val, int number, string objectName, string message = "");
        void IfLowerOrEqualsThan(double val, double number, string objectName, string message = "");
        void IfLowerThan<T>(T model, Expression<Func<T, decimal>> selector, decimal min, string message = "");
        void IfLowerThan(double val, double min, string objectName, string message = "");
        void IfLowerThan<T>(T model, Expression<Func<T, int>> selector, int min, string message = "");
        void IfLowerThan(float val, float min, string objectName, string message = "");
        void IfLowerThan(decimal val, decimal min, string objectName, string message = "");
        void IfLowerThan<T>(T model, Expression<Func<T, double>> selector, double min, string message = "");
        void IfLowerThan(DateTime val, DateTime min, string objectName, string message = "");
        void IfLowerThan(int val, int min, string objectName, string message = "");
        void IfLowerThan<T>(T model, Expression<Func<T, DateTime>> selector, DateTime min, string message = "");
        void IfLowerThan<T>(T model, Expression<Func<T, float>> selector, float min, string message = "");
        void IfNotAreEquals(float val, float value, string objectName, string message = "");
        void IfNotAreEquals<T>(T model, Expression<Func<T, int>> selector, int value, string message = "");
        void IfNotAreEquals(DateTime val, DateTime value, string objectName, string message = "");
        void IfNotAreEquals<T>(T model, Expression<Func<T, decimal>> selector, decimal value, string message = "");
        void IfNotAreEquals<T>(T model, Expression<Func<T, float>> selector, float value, string message = "");
        void IfNotAreEquals(int val, int value, string objectName, string message = "");
        void IfNotAreEquals(double val, double value, string objectName, string message = "");
        void IfNotAreEquals<T>(T model, Expression<Func<T, double>> selector, double value, string message = "");
        void IfNotAreEquals(decimal val, decimal value, string objectName, string message = "");
        void IfNotAreEquals<T>(T model, Expression<Func<T, string>> selector, string text, string message = "");
        void IfNotAreEquals<T>(T model, Expression<Func<T, DateTime>> selector, DateTime value, string message = "");
        void IfNotAreEquals(string val, string text, string objectName, string message = "");
        void IfNotCnpj(string val, string objectName, string message = "");
        void IfNotCnpj<T>(T model, Expression<Func<T, string>> selector, string message = "");
        void IfNotContains(string val, string text, string objectName, string message = "");
        void IfNotContains<T>(T model, Expression<Func<T, string>> selector, string text, string message = "");
        void IfNotCpf(string val, string objectName, string message = "");
        void IfNotCpf<T>(T model, Expression<Func<T, string>> selector, string message = "");
        void IfNotDate<T>(T model, Expression<Func<T, string>> selector, string message = "");
        void IfNotDate(string val, string objectName, string message = "");
        void IfNotEmail<T>(T model, Expression<Func<T, string>> selector, string message = "");
        void IfNotEmail(string val, string objectName, string message = "");
        void IfNotGuid<T>(T model, Expression<Func<T, string>> selector, string message = "");
        void IfNotGuid(string val, string objectName, string message = "");
        void IfNotMatch(string val, string regex, string objectName, string message = "");
        void IfNotMatch<T>(T model, Expression<Func<T, string>> selector, string regex, string message = "");
        void IfNotNull<T>(T model, Expression<Func<T, DateTime>> selector, string message = "");
        void IfNotNull<T>(T model, Expression<Func<T, int?>> selector, string message = "");
        void IfNotNull<T>(T model, Expression<Func<T, object>> selector, string message = "");
        void IfNotNull(object val, string objectName, string message = "");
        void IfNotNull(decimal? val, string objectName, string message = "");
        void IfNotNull(int? val, string objectName, string message = "");
        void IfNotNull<T>(T model, Expression<Func<T, decimal?>> selector, string message = "");
        void IfNotNull(DateTime val, string objectName, string message = "");
        void IfNotNull<T>(T model, Expression<Func<T, double?>> selector, string message = "");
        void IfNotNull(DateTime? val, string objectName, string message = "");
        void IfNotNull(float? val, string objectName, string message = "");
        void IfNotNull(double? val, string objectName, string message = "");
        void IfNotNull<T>(T model, Expression<Func<T, DateTime?>> selector, string message = "");
        void IfNotNull<T>(T model, Expression<Func<T, float?>> selector, string message = "");
        void IfNotNullOrEmpty(string val, string objectName, string message = "");
        void IfNotNullOrEmpty<T>(T model, Expression<Func<T, string>> selector, string message = "");
        void IfNotRange(DateTime val, DateTime a, DateTime b, string objectName, string message = "");
        void IfNotRange<T>(T model, Expression<Func<T, int>> selector, int a, int b, string message = "");
        void IfNotRange<T>(T model, Expression<Func<T, DateTime>> selector, DateTime a, DateTime b, string message = "");
        void IfNotRange(double val, double a, double b, string objectName, string message = "");
        void IfNotRange(int val, int a, int b, string objectName, string message = "");
        void IfNotRange<T>(T model, Expression<Func<T, float>> selector, float a, float b, string message = "");
        void IfNotRange<T>(T model, Expression<Func<T, decimal>> selector, decimal a, decimal b, string message = "");
        void IfNotRange(float val, float a, float b, string objectName, string message = "");
        void IfNotRange(decimal val, decimal a, decimal b, string objectName, string message = "");
        void IfNotRange<T>(T model, Expression<Func<T, double>> selector, double a, double b, string message = "");
        void IfNotUrl(string val, string objectName, string message = "");
        void IfNotUrl<T>(T model, Expression<Func<T, string>> selector, string message = "");
        void IfNull<T>(T model, Expression<Func<T, float?>> selector, string message = "");
        void IfNull(int? val, string objectName, string message = "");
        void IfNull<T>(T model, Expression<Func<T, object>> selector, string message = "");
        void IfNull(decimal? val, string objectName, string message = "");
        void IfNull<T>(T model, Expression<Func<T, decimal?>> selector, string message = "");
        void IfNull<T>(T model, Expression<Func<T, double?>> selector, string message = "");
        void IfNull(DateTime val, string objectName, string message = "");
        void IfNull<T>(T model, Expression<Func<T, DateTime?>> selector, string message = "");
        void IfNull<T>(T model, Expression<Func<T, DateTime>> selector, string message = "");
        void IfNull<T>(T model, Expression<Func<T, int?>> selector, string message = "");
        void IfNull(double? val, string objectName, string message = "");
        void IfNull(float? val, string objectName, string message = "");
        void IfNull(DateTime? val, string objectName, string message = "");
        void IfNull(object val, string objectName, string message = "");
        void IfNullOrEmpty<T>(T model, Expression<Func<T, string>> selector, string message = "");
        void IfNullOrEmpty(string val, string objectName, string message = null);
        void IfNullOrInvalidLength(string val, int min, int max, string objectName, string message = "");
        void IfNullOrInvalidLength<T>(T model, Expression<Func<T, string>> selector, int min, int max, string message = "");
        void IfNullOrWhiteSpace(string val, string objectName, string message = "");
        void IfNullOrWhiteSpace<T>(T model, Expression<Func<T, string>> selector, string message = "");
        void IfRange<T>(T model, Expression<Func<T, double>> selector, double a, double b, string message = "");
        void IfRange(int val, int a, int b, string objectName, string message = "");
        void IfRange<T>(T model, Expression<Func<T, DateTime>> selector, DateTime a, DateTime b, string message = "");
        void IfRange<T>(T model, Expression<Func<T, float>> selector, float a, float b, string message = "");
        void IfRange<T>(T model, Expression<Func<T, decimal>> selector, decimal a, decimal b, string message = "");
        void IfRange(float val, float a, float b, string objectName, string message = "");
        void IfRange<T>(T model, Expression<Func<T, int>> selector, int a, int b, string message = "");
        void IfRange(DateTime val, DateTime a, DateTime b, string objectName, string message = "");
        void IfRange(double val, double a, double b, string objectName, string message = "");
        void IfRange(decimal val, decimal a, decimal b, string objectName, string message = "");
        void IfTrue<T>(T model, Expression<Func<T, bool>> selector, string message = "");
        void IfTrue(bool val, string objectName, string message = "");
    }
}